support modify route entry's name
alibaba/footmark pull request #39
Opened 2019-10-16 08:13 UTC by lixue323

2019-10-16 14:17 UTC, xiaozhu36 requested changes

2019-10-16 14:17 UTC, xiaozhu36 commented on setup.py
> +                      'aliyun-python-sdk-vpc>=3.0.7',
这个还是要限制下版本上限

2019-10-17 02:52 UTC, lixue323 commented on setup.py
> +                      'aliyun-python-sdk-vpc>=3.0.7',
3.0.4开始支持ModifyRouteEntryName, 最新版本3.0.7经测试也没问题，所以版本范围定到这个区间

2019-10-17 03:09 UTC, xiaozhu36 approved these changes

2019-10-17 03:09 UTC, merged