support query instance more than 10 results
alibaba/footmark pull request #40
Opened 2019-10-21 11:28 UTC by lixue323

2019-10-22 04:53 UTC, xiaozhu36 requested changes

2019-10-22 04:53 UTC, xiaozhu36 commented on footmark/ecs/connection.py
> +            if len(inst_list) < 100:
if len(inst_list) < pagesize？

2019-10-22 05:55 UTC, lixue323 commented on footmark/ecs/connection.py
> +            if len(inst_list) < 100:
当前页码返回数量小于pagesize，说明是最后一页，break

2019-10-23 10:41 UTC, xiaozhu36 approved these changes

2019-10-23 10:41 UTC, merged