improve (rds): modify rds instance
alibaba/footmark pull request #53
Opened 2019-11-27 12:12 UTC by lixue323

2019-12-23 09:15 UTC, xiaozhu36 requested changes

2019-12-23 09:15 UTC, xiaozhu36 commented on footmark/connection.py
> +            request.set_connect_timeout(100)
为啥改这个

2019-12-23 09:15 UTC, xiaozhu36 commented on footmark/connection.py
> +        if "DbInstance" in action or "DbDescription" in action:
这个最好严格判断，可以参考下vswitch的

2019-12-23 10:33 UTC, lixue323 commented on footmark/connection.py
> +            request.set_connect_timeout(100)
创建rds instance总是返回超时，sdk开发小伙伴让把这两个值设置的大一些，然后OK了

2019-12-24 07:46 UTC, lixue323 commented on footmark/connection.py
> +        if "DbInstance" in action or "DbDescription" in action:
嗯，这个判断拿到了rds自己的connection中做判断了

2019-12-25 04:22 UTC, xiaozhu36 approved these changes

2019-12-25 04:22 UTC, merged