add ros sdk
alibaba/footmark pull request #79
Opened 2020-04-09 08:00 UTC by q383656225

add ros sdk

2020-04-09 09:01 UTC, lixue323 commented on footmark/ros/connection.py
> +    DefaultRegionName = '北京'.encode("UTF-8")
这快默认region和其它保持一致吧，用杭州

2020-04-09 09:01 UTC, lixue323 commented on footmark/ros/connection.py
> +    def init_connection(self):
这里不用创建client, footmark/connection 中有现成的方法。get_object_new/get_status_new/get_list_new

2020-04-09 09:01 UTC, lixue323 commented on footmark/ros/connection.py
> +    def create_stack(self, stack_name, template_body, parameters, create_timeout, template_type):
参照一下这个代码 https://github.com/alibaba/footmark/blob/644fa27d00163b7e87e0485d428918a60eb6e5cd/footmark/vpc/connection.py#L91

2020-04-09 09:01 UTC, lixue323 commented on footmark/ros/connection.py
> +    def create_stack(self, stack_name, template_body, parameters, create_timeout, template_type):
下面那些方法都是，参照一下其它产品的，你需要在写一个ros.py文件，像其它产品一样

2020-04-13 02:39 UTC, lixue323 commented on footmark/ros/ros.py
> +    def modify(self, template_body, parameterss, timeout_in_minutes):
你这个方法也没用到啊，我看你provider当中直接调的更新方法，应该先调这个，判断参数是否有变化，没变化不去更新，直接返回 ,provider中更新结果为false,有变化调用connection中的更新方法，获取更新结果，在根据结果返回，provider中在判断

2020-04-13 02:39 UTC, lixue323 commented on footmark/ros/ros.py
> +    def delete(self):
创建 删除 你都是直接调用的方法，这里用不到就不用写

2020-04-13 02:39 UTC, lixue323 commented on footmark/ros/ros.py
> +
我看provider中参数并没有全部返回，你想返回哪些参数，就在这里写个read方法，调用这个方法

2020-04-16 13:12 UTC, xiaozhu36 requested changes

2020-04-16 13:12 UTC, xiaozhu36 commented on footmark/ros/connection.py
> +        ros_stack_objs = self.get_list_new(self.build_request_params(self.format_request_kwargs(**kwargs)), ['Ross', ResultSet])
Ross 是啥

2020-04-17 08:57 UTC, closed without merging